name: Github Actions Demo
permissions:
    id-token: write
    pages: write

on:
    push:
        branches: [main]
        paths:
            - index.html
jobs:
    Github-Actions-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: upload index.html
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./

            - name: Deploy website
              uses: actions/deploy-pages@v4
